### ISSUE TITLE
Error when grammar has no rules

### ISSUE THREAD

**Issue by JFinis** [jknack/antlr4ide#69] opened 2014-06-10 14:54 UTC
Antlr4ide issues an error when a grammar has no rules. A ruleless grammar, however, is sometimes useful when using it as `import` into another grammar. Such a grammar can for example only add code blocks instead of rules.

**Comment by arifogel** [comment] 2016-11-06 01:41
Hi I just picked up this project. If you can build this using antlr4 from the command line, then this is an anltr4ide issue. If not, this is an invalid bug (should be posted in antlr4 project instead). If you do not respond within two weeks, I will close this bug as invalid.

**Comment by JFinis** [comment] 2016-11-14 17:48
@arifogel : Your question is answered in my latest post ("My ANTLR does not complain when using such a grammar as import"), so it is indeed an Antlr4ide issue.

A side note, with all due respect:
Have you tried reproducing this and failed or do you just close bug reports without even trying? I did answer in time, but I could have also missed that mail and you would have closed the bug, although it is probably still there and easily reproducible by anyone.

**Comment by arifogel** [comment] 2016-11-14 18:21
You're missing some context here with your reply. This project was
essentially abandoned, and three of us including myself have only just
within the past two weeks started taking over and reviewing the existing
bugs. So we are essentially retriaging them. In this process, reports where
the original reporter is incommunicado should be closed. In case we close
something and the original reporter notices late, it is trivial to request
a bug be reopened. So there is no real risk here.

As to the meat of your reply:
You argue (but it is not necessarily consensus) that grammars need not
stand on their own, if they are intended to be used as imports. I am
leaning against that, frankly. Your use case of importing common members is
better handled by defining a superclass, and using the superclass directive
in the appropriate parent grammar, since this gives access to the Java type
checker. So I am still not convinced any change is necessary. I am,
however, open to counterarguments.
On Nov 14, 2016 9:48 AM, "JFinis" <notifications@github.com> wrote:

> <https://github.com/arifogel>

> @arifogel <https://github.com/arifogel> : Your question is answered in my
latest post ("My ANTLR does not complain when using such a grammar as
import"), so it is indeed an Antlr4ide issue.
>
> A side note, with all due respect:
> Have you tried reproducing this and failed or do you just close bug
reports without even trying? I did answer in time, but I could have also
missed that mail and you would have closed the bug, although it is probably
still there and easily reproducible by anyone.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/jknack/antlr4ide/issues/69#issuecomment-260407398>, or
mute the thread

**Comment by HSorensen** [comment] 2016-11-14 18:31
@JFinis can you provide sample grammars for what you want to achieve. There are some other issues related IMPORT that I will take a look at. See [Project](https://github.com/jknack/antlr4ide/projects/1) your usecase might be valid, but as @arifogel mention we have just begun to revive the development effort of antlr4ide so patience and corporation goes a long way.

**Comment by JFinis** [comment] 2016-11-14 19:43
@arifogel Okay, that makes sense. My counterargument is: ANTLR itself allows it and an IDE should always allow whatever the Compiler/Generator itself allows. Whether @member directives are better than subclassing is a matter of taste, style and other considerations, of course. But an IDE should not dictate the style a programmer should use. 

If you still deem this a misfeature of ANTLR, you can issue a warning, but you should not issue an error, because this means that a valid ANTLR grammar cannot be processed in the IDE. Given that changing this error to a warning or dropping it completely should only be a few lines of code to change and probably less than one hour of work, this bug might be worth fixing.

@HSorensen : To be honest, I am currently not working on the project where I needed this. So I could be indifferent about this feature. I Keep only arguing here for the greater good of correct open source software :).

**Comment by HSorensen** [comment] 2016-11-14 20:59
For now i'll close this issue. If there is a valid usecase we can revisit.
Closed.

**Closed by HSorensen** 2016-11-14 20:59 UTC
Labels: wontfix
