### ISSUE TITLE
ANTLR4 Plugin Fails to start in Eclipse Mars

### ISSUE THREAD

**Issue by steowens** [jknack/antlr4ide#136] opened 2016-01-09 14:43 UTC
Repro steps.  Dowload and install Eclipse MARS (latest).  Open Eclipse Marketplace and Download Antlr 4 IDE (Latest).  Run the installation and allow Eclipse to restart.  Create a new ANTLR project.  

Expected result: Wizard runs and creates a project.

Actual result: Error Dialog with the message: Problem Opening Wizard \n The Selected Wizard Could not be Started

Details: the selected wizard could not be started.
Failed to create injector for com.github.jknack.antlr4ide.Antlr4 ExtensionFactory: com.github.jknack.antlr4ide.ui.Antlr4ExecutableExtensionFactory
Failed to create injector for com.github.jknack.antlr4ide.Antlr4

**Comment by kozchris** [comment] 2016-02-10 20:17
I can confirm this is happening also. As an additional data point I have Xtext 2.9.0 installed.

**Comment by JLevinCA** [comment] 2016-02-11 15:40
Ditto, I just upgraded to Mars from Luna.  Any attempt to open a g4 file now causes an error similar to the one steepness reported.

org.eclipse.core.runtime.CoreException: Failed to create injector for com.github.jknack.antlr4ide.Antlr4 ExtensionFactory: com.github.jknack.antlr4ide.ui.Antlr4ExecutableExtensionFactory
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:59)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:262)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:284)
	at org.eclipse.ui.internal.registry.EditorDescriptor.createEditor(EditorDescriptor.java:235)
	at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:328)

**Comment by autohandle** [comment] 2016-03-07 20:51
me 2

**Comment by eclipser42** [comment] 2016-03-31 11:44
#134 is the same symptom, with a few suggested workarounds.

**Comment by autohandle** [comment] 2016-03-31 14:00
this link is better
http://stackoverflow.com/questions/30128961/trouble-setting-up-antlr-4-ide-on-eclipse-luna-4-4

**Comment by rensink** [comment] 2016-04-15 09:30
@autohandle: the stackoverflow question has nothing to do with the issue discussed here.

See the link by @eclipser42 for a workaround solution (involving the installation of the old XText version 2.7.3)

**Comment by arifogel** [comment] 2016-05-13 00:07
I've patched this issue in Luna, at least. I have yet to test in Mars, since Mars sucks on my machine.. See my pull request: https://github.com/jknack/antlr4ide/pull/144

**Comment by donizyo** [comment] 2016-06-14 05:29
Then one must use Luna to use the plugin?

**Comment by arifogel** [comment] 2016-06-14 11:20
I have built in Windows 10 from cmd using maven 3 and my patch from pull request #144 and jdk 1.7.0_80 and xtext 2.9.2 (must install in eclipse before installing antlr4ide) successfully installed and used antlr4ide in Eclipse Mars. I could not get Mars working AT ALL in Ubuntu 16.04 (GTK3 issues I think), so I did not test for that.

**Comment by arifogel** [comment] 2016-06-14 11:38
To save everyone trouble, I've created a release of antlr4ide as built above at my fork at:
https://github.com/arifogel/antlr4ide/releases/tag/0.3.6-arifogel

**Comment by donmendelson** [comment] 2016-07-01 17:57
I encountered the same problem with both Eclipse Mars and Neon

**Comment by BurtHarris** [comment] 2016-07-04 19:49
I've confirmed that @arifogel's pre-release works for me, with Eclipse Neon and Xtext 2.10.0 on Windows 10.

I'd like to help, but I really don't understand the issue blocking pull request #144.  It seems to me like the root problem has been outstanding for a long time.   

Perhaps it would help to move this project to a github organization, perhaps @antlr where more people might contribute.

**Comment by nmusatti** [comment] 2016-07-04 21:15
I may be mistaken, but I'm under the impression that @jknack is not very interested in this project any more. Maybe it really is time it was forked.

**Comment by BurtHarris** [comment] 2016-07-06 21:01
It sort of looks that way.   I took a fork and played with it some.   It seems to me like there are dependencies (perhaps only test dependencies) on packages that haven't been kept up either, so for example building it with Oracle JDK 8 results in test failures.   I don't understand what license terms it has been released under, nor know enough about Java's version of dependency hell to tackle that myself.   I wonder if @parrt might be helpful in choosing a path forward.

**Comment by parrt** [comment] 2016-07-06 21:03
Hiya. Sorry but I'm not sure what @jknack's up to.

**Comment by BurtHarris** [comment] 2016-07-06 21:23
Hi Terrence.   Thanks for ANTLR 4.

I gather you're using IntelliJ rather than Eclipse, perhaps I'll do the same.   I guess the question for you is if you might want to take this project under the wing of  @antlr , perhaps releasing @arifogel's fix to this issue.

**Comment by parrt** [comment] 2016-07-07 00:12
Hmm...well, since I don't do anything with eclipse, I'd have to learn something, which takes effort I don't have at moment. :(  Can you just use this fork?

**Comment by jknack** [comment] 2016-07-07 00:38
Hi guys!

Same here, I don't have time to review and fix for now... but also don't think it's to hard to make the upgrade/fix to latest Eclipse.

Plugin is released with Apache License so you're free to fork, release etc...or if someone (probably you @arifogel) want to share the ownership of this project or make you a team member/collaborator.

Thanks.

**Comment by arifogel** [comment] 2016-07-07 01:10
It seems there are two issues here:
1. Someone needs to take over Eclipse release management. This requires delegation from @jknack, or else we will have to move canonical development to another fork and possibly rename the project in the Eclipse marketplace.
2. Someone needs to take over development and build management.
Unfortunately, I don't really have time to do either.

**Comment by RedTailedHawk** [comment] 2016-07-07 14:33
Thanks @arifogel, your version seems to be working for me under Neon and Xtext 2.10.0.

**Comment by arifogel** [comment] 2016-11-05 19:59
Fixed by pull request #144.

**Closed by arifogel** 2016-11-05 19:59 UTC
